import Head from 'next/head'
import Image from 'next/image'

//#region Components
import CollectionSection from '@/components/Collections/CollectionSection';
import HeroSection from '@/components/Hero/HeroSection';
import AboutSection from '@/components/About/AboutSection';
import AboutFullSection from '@/components/About/AboutFullSection';
import NewCollectionsSection from '@/components/Collections/NewCollectionsSection';
//#endregion

export default function Home() {



  return (
    <>
      <Head>
        <title>Decovita</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <HeroSection />
        <CollectionSection />
        <AboutSection />
        <AboutFullSection />
        <NewCollectionsSection />
      </main >
    </>
  )
}


