import Head from 'next/head'
import Image from 'next/image'

//#region Components
import CollectionSection from '@/components/Collections/CollectionSection';
import HeroSection from '@/components/Hero/HeroSection';
//#endregion

export default function Home({ SliderData, CategoryData }) {

  

  return (
    <>
      <Head>
        <title>Decovita</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <HeroSection SliderData={SliderData} />

        <CollectionSection CategoryData={CategoryData} />
      </main >
    </>
  )
}


export const getServerSideProps = async (context) => {

  const SliderRes = await fetch(process.env.URL + '/api/slider');
  const SliderData = await SliderRes.json();

  const CategoryRes = await fetch(process.env.URL + "/api/categories");
  const CategoryData = await CategoryRes.json();

  return {
    props: {
      SliderData,
      CategoryData
    }
  }
}